### ISSUE TITLE
Lassie HTTP + booster-http tracking issue

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/boost#1389]
# What

We want Lassie to download over HTTP from booster-http. This issue tracks what is needed for this to happen.

# Components

Updated 6/12/23 to reflect current state and detailed steps to merge

- [x] Boxo support for IPIP-402 parameters **6/12/23 -- released in boxo v0.10.0**
- [ ] Bubble Boxo through to boost - **DRI: Tornado** (some of this work may be done Stewards, but Tornado is responsible for watching, monitoring, assisting, and making sure this gets done)
   - [ ] resolve go-merkledag issue https://github.com/ipfs/boxo/issues/291 **6/12/23 -- is this done?**
   - [ ] complete go-fil-markets boxo migration https://github.com/filecoin-project/go-fil-markets/pull/792 **Hannah to take over**
   - [ ] complete Lotus Boxo migration https://github.com/filecoin-project/lotus/pull/10921 **Hannah to take over**
   - [ ] complete Boost GFM migration https://github.com/filecoin-project/boost-gfm/pull/2 
   - [ ] complete Boost integration https://github.com/filecoin-project/boost/pull/1492 (note: this may not ultimately be mergable till all of the above are in tagged releases)
- [ ] https://github.com/filecoin-project/boost/issues/1407 - PR is in (https://github.com/filecoin-project/boost/pull/1418), but appears abandoned. @dirkmc do you want to finish this? should Tornado?
- [ ] local devnet test between Lassie and Boost, using direct peer fetching **DRI: Tornado**
- [ ] fil-collins test round trip with Lassie and Boost, with indexer integration **DRI: Tornado with support from Boost**
- [ ] external SP testing as needed prior to release **DRI: Boost**
- [ ] update to tagged dependency releases and merge final boost PR, cut Boost release **DRI: Boost**

**Comment by jacobheun** [comment]
Thanks for creating this and linking to the various depencies @hannahhoward, super helpful ❤️

**Comment by davidd8** [comment]
@hannahhoward can we add a task around metrics cleanup for http retrievals attempts for SPs to distinguish from other HTTP providers, like web3.storage?
