### ISSUE TITLE
[Epic] Handling non-car files within Boost

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/boost#1685]
_This is the parent tracking issue related to the handling of non-car files within Boost._

# Problem Statement
The current design of Boost assumes that all the deals are made with car files. There is no provision to handle a deal which might be blobs of data or concatenate car files (data segment indexing).  

# Change Proposal
To successfully handle the non-car files, we need to make multiple changes in Boost architecture and internal deal flow. These changes would need to be shipped in a single release to avoid breaking any existing functionality and introducing new bugs. The list of required changes is below along with their tracking issues or PRs

## Merge all the new changes to a feature branch

- [ ] Create a new feature branch
- [ ] Rebase all existing PRs to the new feature branch

## Handle commP for non-car file

- [ ] [Boost should allow generating commP for non-car files](https://github.com/filecoin-project/boost/pull/1651)

## Handle generating index for concatenate car files (data segment indexing)

- [ ] [Update PieceDirectory to generate indexes for concatenate car files](https://github.com/filecoin-project/boost/pull/1495)

## Handle deal flow error for non-car files

- [ ] Update adding deals to LID to account for non-car files as we cannot generate index for them

## Update piece-doctor

- [ ] Update piece-doctor to not generate indexing alerts in UI for non-car pieces
- [ ] Update LID UI to show how many non-car pieces we have

## Handle LID recovery for non-car file

- [ ] Update LID recovery tool to account for non-car files (This would need be implemented along with changes required to recover without onChain details about the deals)

## Update Boost docs

- [ ] Update Boost docs to explain the new capabilities and LID changes
