### ISSUE TITLE
[Epic] LID cleanup

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/boost#1709]
_This is the parent tracking issue related cleanup of indexes and deals from LID within Boost._

# Problem Statement
Since the launch of Lotus, there have been no clean up policy in place for the metadata of expired or lost deals. We carried this behaviour into Boost and Boost v2 as well. After the launch of LID, this old metadata has become a nuisance causing the following problems.
1. Indexers still have old indexes for expired deals carried forwarded from lotus markets. 
2. These older indexes lead to a higher failure rate of retrievals by validation bots.
![image (9)](https://github.com/filecoin-project/boost/assets/88259624/69bb9da3-9018-48c3-9838-ae04271e6045)

3. When a new deals is lost (sector loss  for any reason), we still don't clean up the deal details even though it serves no purpose. This leads to accumulation of indexes which are just occupying space on the DB.
4. Inconsistencies in the state of a piece and indexes when same piece refers to old removed/expired deals and new healthy deals

# Change Proposal
Filecoin's main USP is Proof of spacetime. The argument that SPs can continue to serve the data even after sector expires without any incentive seems a bit premature. This epic propose the following changes to the existing deal flow and how LID cleans up the data.

- [ ] Clean up older deals from LID with a background job
    - [ ] The background job frequency must be configurable
    - [ ] The background job must also check deal expiration and clean up the expired deals. This should also take into account the sector state manager
    - [ ] An removal ad must be sent for each deal so indexers can be update about the new state of SP
- [ ] Clean up new deal from LID if sector reaches a final state other than `proving`
    - [ ] Boost must check that sector actually contains the deal when it reached the proving state for snap deals
