### ISSUE TITLE
Remaining tasks for Boost Estuary acceptances testing

### ISSUE THREAD

**Issue by aarshkshah1992** [filecoin-project/boost#257]
### TODO

- [x]  Ensure we check for context cancellation in publish, publish confirm and addpiece RPC messages.
- [x] Ensure a deal starts sealing.
- [x]  Fire 10 1G concurrent deals from Estuary and ensure they start sealing inspite of multiple Boost restarts.
- [x] Unflake `TestDealRejectedForFunds`.
- [ ] PR to make `AddPiece` idempotent and test on Sofia Miner.
- [x] Better logging for Boost shutdown to see where it gets stuck.
