### ISSUE TITLE
Bitswap support in Boost for free IPFS retrievals from Filecoin

### ISSUE THREAD

**Issue by aarshkshah1992** [filecoin-project/boost#375]
### TODO

- [ ] DAGStore exposes a read only blockstore across all the deals (legacy & Boost) (https://github.com/filecoin-project/dagstore/pull/116/).
- [ ] Boost instantiates a Bitswap server using the all shards blockstore.
- [ ] Boost announces itself as provider for each of it's deal cids over Bitswap using the Index Provider.
- [ ] Ensure the Bitswap index announcement records flow to the Index Provider.
- [ ]  Test Bitswap retrievals from Boost using an IPFS instance or the Bitswap testing tool.

**Comment by jacobheun** [comment]
Closing this as a duplicate of https://github.com/filecoin-project/boost/issues/348. I've added the TODO's there.
