### ISSUE TITLE
Sample Docker compose with a Boost container for deal-making

### ISSUE THREAD

**Issue by airenas** [filecoin-project/boost#695]
@laurenspiegel: *After speaking with the team further, the most helpful thing would actually be setting up docker compose with a Boost container for deal-making, a Boost container for the UI and a Lotus container all in dev mode to make running locally for devs (or any first-time users of the software) easier.*

**Expected result**: user having docker locally can test `boost`, and make a deal without needing to compile `lotus` and `boost` repos.

**Tools to be containerized**:
 - `lotus`
 - `lotus-seed`
 - `lotus-miner`
 - `devnet` (from boost repo)?
 - `boost`
 - `boostd`
 - `boostx`
 - `boost` react GUI 

**Tasks**:
- [x] Dockerfile for packing `lotus` tools in dev mode.
- [x] Dockerfile for packing `boost`: containing `boost`, `boostd`, `boostx`.
- [x] Dockerfile for `boost` GUI. 
- [x] Compose file for orchestrating everything.
- [x] Makefile scripts for building docker containers.
- [x] Doc with samples on how to make a deal using the compose file.

**Comment by airenas** [comment]
Do we need a separate container for `boost` GUI? According to the [devnet doc](https://github.com/filecoin-project/boost/blob/main/documentation/devnet.md): 1) We start `boostd -vv run`, and 2) we should access *http://localhost:8080/ to see the Boost UI*. But, for me, it did not work, I had to run GUI with npm and access at  a port `3000`

**Comment by jacobheun** [comment]
> Do we need a separate container for boost GUI?

The GUI is run separately from the daemon as it's not actually required for operations, so another container would make sense for this.

**Comment by airenas** [comment]
Another question regarding `lotus`. 
I started `lotus` (compiled with `make debug`) in a docker container. It runs. And I want to access it from another container. `lotus auth api-info --perm=admin` gives me just a local address `.../ip4/127.0.0.1/tcp/1234/http`. I know the container's IP, I try to telnet to the container's port 1234, but no one listens. It looks like `lotus` does not listen to the remote network interface. I tried to set env `LOTUS_API_REMOTELISTENADDRESS=173.2.0.22:1234`. No success. Any ideas on how to configure it?

**Comment by LaurenSpiegel** [comment]
@LexLuthr , can you please help here when you have a minute?

**Comment by airenas** [comment]
> Another question regarding `lotus`. I started `lotus` (compiled with `make debug`) in a docker container. It runs. And I want to access it from another container. `lotus auth api-info --perm=admin` gives me just a local address `.../ip4/127.0.0.1/tcp/1234/http`. I know the container's IP, I try to telnet to the container's port 1234, but no one listens. It looks like `lotus` does not listen to the remote network interface. I tried to set env `LOTUS_API_REMOTELISTENADDRESS=173.2.0.22:1234`. No success. Any ideas on how to configure it?

Setting `LOTUS_API_LISTENADDRESS` (not `LOTUS_API_REMOTELISTENADDRESS`) has helped.

**Comment by LexLuthr** [comment]
@airenas I will test boost within container and get back to you with all required configs and possible deployment strategies tomorrow. I have tested lotus but I have tested boost with lotus so it might take me a little while to set everything up correctly and figure out all the pitfalls.

**Comment by LaurenSpiegel** [comment]
@airenas , are you unstuck now? if so, I think @LexLuthr can pause on this.

**Comment by airenas** [comment]
> @airenas , are you unstuck now? if so, I think @LexLuthr can pause on this.

Yes, I'm good now. At the time no help is needed, thanks @LexLuthr.
