### ISSUE TITLE
[Epic] Add support for the Bitswap transport

### ISSUE THREAD

**Issue by jacobheun** [filecoin-project/boost#709]
## Summary
Storage Providers should be able to serve requests to the IPFS network as several storage clients, such as [web3.storage](http://web3.storage/), Estuary, and IPFS pinning services, and their end users are part of the IPFS network. Adding support for Bitswap removes the need for intermediary services, such as [autoretrieve](https://github.com/application-research/autoretrieve). Leveraging the flexibility of Boost we should enable this as a standalone service, similar to `booster-http`, so that it can be independently scaled as needed.

As part of this effort we are working with the [Kubo](https://github.com/ipfs/kubo) and IPFS.io gateway teams to enable e2e tracing of the retrieval pipeline as part of our efforts to improve retrieval reliability. This will ensure we have visibility into each component in the retrieval pipeline to better resolve reliability and performance issues. The metrics/logging added for Boost will also enable us to troubleshoot retrieval problems seen by other retrieval transports (Graphsync and HTTP) at lower layers of the Boost code base (DAG store, piece store, etc)

### 1. E2E Integration with Kubo for free, public content
With the completion of this milestone Kubo will be able to query Network Indexers, such as [cid.contact](https://cid.contact/), for a given CID and discover SP's who are running the Bitswap transport.

#### Requirements
* SP's must be able to restrict access to content via existing retrieval access patterns
* Only 0 cost retrieval will initially be supported
* Bitswap content records should be discoverable on network indexers, such as cid.contact

##### Enabling the Bitswap retrieval server
- [x] Add support for a standalone Bitswap retrieval service - https://github.com/filecoin-project/boost/pull/707
- [x] https://github.com/filecoin-project/boost/issues/711
- [x] https://github.com/filecoin-project/boost/issues/716
- [x] https://github.com/filecoin-project/boost/issues/731
##### Adding metrics/logging
- [x] https://github.com/filecoin-project/boost/issues/772
- [ ] Audit the [split bitswap server](https://github.com/ipfs/go-bitswap/issues/568) tracing to determine what data is currently being tracked, and what, if any additional tracking we need
  - [ ] Supplement the bitswap server tracing code if needed
- [ ] https://github.com/filecoin-project/boost/issues/365
  - [ ] Add support for uploading these to a central service for the Boost team to analyze
- ...

##### Related Issues
- [ ] https://github.com/ipfs/kubo/issues/9150
- [X] https://github.com/ipfs/go-bitswap/issues/568

## References & Related Items
* [IPFS Gateway <> SP Planning](https://www.notion.so/pl-strflt/IPFS-Gateway-To-Filecoin-Planning-7659f424f89d434694dfb2ceb283526b)
* https://github.com/filecoin-project/boost/issues/645

**Comment by dirkmc** [comment]
It will run as a service that is started separately from the boostd process

**Comment by jacobheun** [comment]
Shipped with https://github.com/filecoin-project/boost/releases/tag/v1.5.1
